name: Coverage On Pull-Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Show NodeJS version
      run: node -v

    - name: Install dependencies
      run: yarn install

    - name: Run coverage
      run: make coverage
